### ISSUE TITLE
No updates anymore

### ISSUE THREAD

**Issue by Murthy10** [geometalab/Zebrastreifen-Safari#13]
@das-g since the db update there are no new entries shown on http://zebrastreifen-safari.osm.ch/

**Comment by das-g** [comment]
I thought I had granted to role `zebrastreifen` all the same permissions as to role `readonly` on DB `gis_db`, but apparently something was still missing.

I've now run the following on `gis_db`:
```sql
GRANT SELECT ON ALL TABLES IN SCHEMA public TO zebrastreifen;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO zebrastreifen;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO zebrastreifen;
```

I hope this suffices. The query I've seen failing in the postgresql log seems to go through for `zebrastreifen` now.
